services:
  kzhikcn-api:
    container_name: kzhikcn-api
    image: ghcr.io/k05a4b/kzhikcn-api:latest
    ports:
      - 5083:5083
    environment:
      - JWT_SECRET=your_jwt_secret1					 # jwt密钥
      - WEBSITE_NAME=your_website_name 				 # 站点名字（RSS/Sitemap相关）
      - WEBSITE_DESCRIPTION=your_website_description # 网站描述 （RSS/Sitemap相关）
      - WEBSITE_URL=https://example.com				 # 网站URL （RSS/Sitemap相关）
      - ADDRESS=:5083								 # 监听地址

    volumes:
      - ./.tmp/data:/app/data
      - ./.tmp/sys:/app/sys

    restart: always